version: '3.8'

services:
  postgres_ats:
    image: postgres:15-alpine
    container_name: ats_db_container
    environment:
      POSTGRES_DB: ats_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
